In [1]:
import pandas as pd

In [2]:
info = {
    "Name" : ["Anshika", "Kundan", "Shourya", "Shradha"],
    "CGPA" : [9.13, 9.15, 9.00, 9.3],
    "Gender" : ['F', 'M', 'M', 'F']
}

df = pd.DataFrame(info)

print(df)

      Name  CGPA Gender
0  Anshika  9.13      F
1   Kundan  9.15      M
2  Shourya  9.00      M
3  Shradha  9.30      F

In [3]:
df

      Name  CGPA Gender
0  Anshika  9.13      F
1   Kundan  9.15      M
2  Shourya  9.00      M
3  Shradha  9.30      F

In [6]:
# Series in Pandas

s = pd.Series([12, 3, 45, 18, 90])
print(s)

0    12
1     3
2    45
3    18
4    90
dtype: int64

In [17]:
# Defining the label of series

s = pd.Series([23, 34, 20], index = ["Ross", "Joey", "Chandler"])
print(s)
print(s["Ross"])
print(s["Chandler"])
print(s.index)

Ross        23
Joey        34
Chandler    20
dtype: int64
23
20
Index(['Ross', 'Joey', 'Chandler'], dtype='object')

In [15]:
# Vectorizede Operations

s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
#print(s1+s2)
s1[0] = 100
print(s1)
change_s1 = s1.drop(0)
print(change_s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [10]:
# DataFrame creation

#Using Dictionary
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Age" : [20, 23, 21],
    "Cgpa" : [8.35, 9.00, 7.8]
}

df = pd.DataFrame(info)

df

   Name  Age  Cgpa
0  Adam   20  8.35
1   Eve   23  9.00
2   Bob   21  7.80

In [11]:
# List of Lists

df = pd.DataFrame([["Adam", 20], ["Eve", 23], ["Bob", 21]], columns = ["Nmae", "Age"])
df

   Nmae  Age
0  Adam   20
1   Eve   23
2   Bob   21

In [13]:
# Using np Arrays

import numpy as np

np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr, columns = ["A", "B", "C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6